<?php
/**
 * Created by PhpStorm
 * author :gogochen
 * date   :2020/5/7
 * time   :22:36
 */
namespace app\admin\controller;


use app\BaseController;
use think\exception\HttpResponseException;
use think\response\Redirect;

class AdminBase extends BaseController
{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //判断登录,切换到中间件Auth
        if(empty($this->isLogin())){
            return $this->redirect(url('login/index'),302);
        }
    }

    /**
     * 判断登录
     * @return bool
     */
    public function isLogin()
    {
        $this->adminUser = session(config('admin.session_admin'));
        if (empty($this->adminUser)){
            return false;
        }
        return true;
    }

    /**
     * 跳转判断
     * @param mixed ...$args  动态参数
     */
    public function redirect(...$args)
    {
        throw new HttpResponseException(redirect(...$args));
    }
}