<?php
/**
 * Created by PhpStorm
 * author :gogochen
 * date   :2020/5/17
 * time   :22:33
 */


namespace app\api\controller;

/**
 * 登录时继承
 */
class AuthBase extends ApiBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header('access_token');
        if (!$this->accessToken || !$this->isLogin()) {
            return $this->show(config('status.not_login'), "没有登录");
        }
    }

    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin()
    {
        $userInfo = cache(config('redis.token_pre') . $this->accessToken);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['id'] && !empty($userInfo['username']))) {
            $this->userId = $userInfo['id'];
            $this->username = $userInfo['username'];
            return true;
        }
        return false;

    }
}